name: MySQL Build
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  actions: read

jobs:
  build-xrdp-utils:
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        # - name: "Optimize Disk Space"
        #   uses: "hugoalh/disk-space-optimizer-ghaction@v0.8.0"
        #   with:
        #     operate_sudo: "True"
        #     general_include: ".+"
        #     docker_include: ".+"
        #     docker_prune: "True"
        #     docker_clean: "True"
        #     apt_prune: "True"
        #     apt_clean: "True"
        #     homebrew_prune: "True"
        #     homebrew_clean: "True"
        #     npm_prune: "True"
        #     npm_clean: "True"
        #     os_swap: "True"

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Get current date and time
          id: datetime
          run: |
            echo "timestamp=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_OUTPUT
            echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
            echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

        # - name: Login to Docker Hub
        #   uses: docker/login-action@v3
        #   with:
        #     registry: docker.io
        #     username: ${{ secrets.DOCKER_USERNAME }}
        #     password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build XRDP with PulseAudio support
          run: |
            # Build the Docker image with the XRDP and PulseAudio modules
            docker build -f MySQL-Build-Docker/Dockerfile -t mysql-builder .

            # check the image is available
            docker images | grep mysql-builder

            # check the system diskspace
            df -h